# Generated by Django 5.1.3 on 2025-01-30 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('tache', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tâche',
            name='assigné_a',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tâche',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tâche',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
